---
http_interactions:
- request:
    method: get
    uri: "<%= dataprovider_api_base_url %>/api/v1/fetch/users/queries/find_by_mobile?friend=FaGUU1xx60N2cOufnV1v&phones%5B%5D=%2B380987777777"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Www-Authenticate:
      - Digest realm="Zazo DataProvider", qop="auth", algorithm=MD5, nonce="MTQ3MDgxODAzNDoxMzQ3MzQzM2UyMjdiZjBhOTYzOGRlNGI0ZWI0MjhhMA==",
        opaque="822778b6350cbc116426dfdce7488072"
      Content-Type:
      - text/html; charset=utf-8
      Cache-Control:
      - no-cache
      X-Request-Id:
      - da1840e0-7b80-4931-8494-a76924eb059c
      X-Runtime:
      - '1.721647'
      Date:
      - Wed, 10 Aug 2016 08:33:54 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: '{"status":"unauthorized"}'
    http_version: 
  recorded_at: Wed, 10 Aug 2016 08:33:54 GMT
- request:
    method: get
    uri: "<%= dataprovider_api_base_url %>/api/v1/fetch/users/queries/find_by_mobile?friend=FaGUU1xx60N2cOufnV1v&phones%5B%5D=%2B380987777777"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Content-Type:
      - application/json; charset=utf-8
      Cache-Control:
      - no-store, must-revalidate, private, max-age=0
      X-Request-Id:
      - 2a3b2324-8321-4682-87cd-9782a1cc10a3
      X-Runtime:
      - '2.420881'
      X-Miniprofiler-Ids:
      - '["1eapw6o4k92pzipi3iam","62n1eq6wvlp2wyt02wfj","vrm6xgfikgeth0x5f2qw","756wbdn4de8r8k9gfk7e","cs4zdx39wqshi5vuc9y5","g0xs5blfp5u7rvmqu50p","ubgu43dkwywpqc690io5","pzho6r2go1rtd16r713v","gsf5es2klxmysfzk1xcm","dviaj7f583ewzv361dbv"]'
      Date:
      - Wed, 10 Aug 2016 08:33:56 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":2956,"mkey":"YRn7ZUDIZI3WzdKT8WxA"}'
    http_version: 
  recorded_at: Wed, 10 Aug 2016 08:33:56 GMT
- request:
    method: get
    uri: "<%= dataprovider_api_base_url %>/api/v1/fetch/users/queries/attributes?attrs%5B%5D=first_name&attrs%5B%5D=friends&attrs%5B%5D=id&attrs%5B%5D=last_name&user=YRn7ZUDIZI3WzdKT8WxA"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Www-Authenticate:
      - Digest realm="Zazo DataProvider", qop="auth", algorithm=MD5, nonce="MTQ3MDgxODAzNzoyNGNlYzNiNjMzNTQwNDJkYjBmZjYyZTczMGI2Y2UzOA==",
        opaque="822778b6350cbc116426dfdce7488072"
      Content-Type:
      - text/html; charset=utf-8
      Cache-Control:
      - no-cache
      X-Request-Id:
      - de8711cc-2374-434b-bd53-9518587c9393
      X-Runtime:
      - '0.223236'
      Date:
      - Wed, 10 Aug 2016 08:33:57 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: '{"status":"unauthorized"}'
    http_version: 
  recorded_at: Wed, 10 Aug 2016 08:33:57 GMT
- request:
    method: get
    uri: "<%= dataprovider_api_base_url %>/api/v1/fetch/users/queries/attributes?attrs%5B%5D=first_name&attrs%5B%5D=friends&attrs%5B%5D=id&attrs%5B%5D=last_name&user=YRn7ZUDIZI3WzdKT8WxA"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Content-Type:
      - application/json; charset=utf-8
      Cache-Control:
      - no-store, must-revalidate, private, max-age=0
      X-Request-Id:
      - 8e2411bd-b82d-40db-a768-20709ac41141
      X-Runtime:
      - '1.139322'
      X-Miniprofiler-Ids:
      - '["tgtwf1nrr71vnem8m1wz","62n1eq6wvlp2wyt02wfj","vrm6xgfikgeth0x5f2qw","756wbdn4de8r8k9gfk7e","cs4zdx39wqshi5vuc9y5","g0xs5blfp5u7rvmqu50p","ubgu43dkwywpqc690io5","pzho6r2go1rtd16r713v","gsf5es2klxmysfzk1xcm","dviaj7f583ewzv361dbv"]'
      Date:
      - Wed, 10 Aug 2016 08:33:58 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":2956,"first_name":"Nexus","last_name":"NexusInna","friends":["emw7coRpjFHjlRm9lnCc","r7ygnuVrWz51JHRn2tAk","quLw5xZTWegtkoqPq8T3","qsYCPjQwDckShQiJprZi","tIjtGAKdVfhdQLHaoT61","fYbsViwlH8JsVNPJnPx3","8uRHzF9Fb16tYtxH8Ue9","YPStb3UUCtiI5HODkNjZ","pInNcBaUIl66SC6BMOfV","FhPEDt2GUfZkQxYavgtM","upqryKcdvuZp5mlecmn8","FaGUU1xx60N2cOufnV1v","BsHCNf0SYI8CJv91x48W","offmAM4QV5djegwFLqtl","dCeqXNEefoGA8Otu1iCd","LsNUXNH9nBcpHkJGUgU7","5yUd5BIAdoCzNGb2aEZG","j49wNVTmRXCT5Yuf9uAw","d0yE3NErwqcJl1lMC8bW","RMte5GDviJ4DLoH5jstN","HzHsEoCqnu95eisFDQeD","ghc6tcVEhebZZvYeixCz"]}'
    http_version: 
  recorded_at: Wed, 10 Aug 2016 08:33:58 GMT
- request:
    method: get
    uri: "<%= dataprovider_api_base_url %>/api/v1/fetch/users/queries/find_by_mobile?friend=FaGUU1xx60N2cOufnV1v&phones%5B%5D=%2B16507800181"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Www-Authenticate:
      - Digest realm="Zazo DataProvider", qop="auth", algorithm=MD5, nonce="MTQ3MDgxODAzODowMTU0NDBmMTE4YTA1MDdhMmI0OTczY2ZhNzNlYjBkYg==",
        opaque="822778b6350cbc116426dfdce7488072"
      Content-Type:
      - text/html; charset=utf-8
      Cache-Control:
      - no-cache
      X-Request-Id:
      - 57833b04-ab71-44eb-9c5b-31d55adc745a
      X-Runtime:
      - '0.335534'
      Date:
      - Wed, 10 Aug 2016 08:33:58 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: '{"status":"unauthorized"}'
    http_version: 
  recorded_at: Wed, 10 Aug 2016 08:33:58 GMT
- request:
    method: get
    uri: "<%= dataprovider_api_base_url %>/api/v1/fetch/users/queries/find_by_mobile?friend=FaGUU1xx60N2cOufnV1v&phones%5B%5D=%2B16507800181"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Content-Type:
      - application/json; charset=utf-8
      Cache-Control:
      - no-store, must-revalidate, private, max-age=0
      X-Request-Id:
      - 5660319b-4706-46bf-9d3f-0c74fc5ccb3d
      X-Runtime:
      - '1.103837'
      X-Miniprofiler-Ids:
      - '["gcwcwmhxkas8ty1rv6qx","62n1eq6wvlp2wyt02wfj","vrm6xgfikgeth0x5f2qw","756wbdn4de8r8k9gfk7e","cs4zdx39wqshi5vuc9y5","g0xs5blfp5u7rvmqu50p","ubgu43dkwywpqc690io5","pzho6r2go1rtd16r713v","gsf5es2klxmysfzk1xcm","dviaj7f583ewzv361dbv"]'
      Date:
      - Wed, 10 Aug 2016 08:33:59 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":1,"mkey":"yKCS3YZwl1bWbuIFNLE0"}'
    http_version: 
  recorded_at: Wed, 10 Aug 2016 08:33:59 GMT
- request:
    method: get
    uri: "<%= dataprovider_api_base_url %>/api/v1/fetch/users/queries/attributes?attrs%5B%5D=first_name&attrs%5B%5D=friends&attrs%5B%5D=id&attrs%5B%5D=last_name&user=yKCS3YZwl1bWbuIFNLE0"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Www-Authenticate:
      - Digest realm="Zazo DataProvider", qop="auth", algorithm=MD5, nonce="MTQ3MDgxODAzOTo1ODE2NTBiZDRjM2M0Yjg5YmVmYWNlMzc0NTk2OTEwNA==",
        opaque="822778b6350cbc116426dfdce7488072"
      Content-Type:
      - text/html; charset=utf-8
      Cache-Control:
      - no-cache
      X-Request-Id:
      - 866aa6d2-facd-489d-bf08-1a279b99ccac
      X-Runtime:
      - '0.222832'
      Date:
      - Wed, 10 Aug 2016 08:33:59 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: '{"status":"unauthorized"}'
    http_version: 
  recorded_at: Wed, 10 Aug 2016 08:33:59 GMT
- request:
    method: get
    uri: "<%= dataprovider_api_base_url %>/api/v1/fetch/users/queries/attributes?attrs%5B%5D=first_name&attrs%5B%5D=friends&attrs%5B%5D=id&attrs%5B%5D=last_name&user=yKCS3YZwl1bWbuIFNLE0"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Content-Type:
      - application/json; charset=utf-8
      Cache-Control:
      - no-store, must-revalidate, private, max-age=0
      X-Request-Id:
      - 7358d0dc-011e-4983-829d-772426a393ed
      X-Runtime:
      - '1.125914'
      X-Miniprofiler-Ids:
      - '["yole491lty8gkko15nvs","62n1eq6wvlp2wyt02wfj","vrm6xgfikgeth0x5f2qw","756wbdn4de8r8k9gfk7e","cs4zdx39wqshi5vuc9y5","g0xs5blfp5u7rvmqu50p","ubgu43dkwywpqc690io5","pzho6r2go1rtd16r713v","gsf5es2klxmysfzk1xcm","dviaj7f583ewzv361dbv"]'
      Date:
      - Wed, 10 Aug 2016 08:34:01 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":1,"first_name":"iPad","last_name":"Rinat","friends":["cvXvBtGRMqsafH6WdeHr","WBDnxHS1MWXyDqS5VisR","J3BjsUuQNOGrtnI5D0hV","rCjSwpr9R9KaCnL7gRdf"]}'
    http_version: 
  recorded_at: Wed, 10 Aug 2016 08:34:01 GMT
recorded_with: VCR 3.0.3
