defaults: &defaults
  app_name: Zazo FriendFinder
  app_name_key: friendfinder
  version: 0.6.0
  email_notification_from: 'Zazo Notifications <support@zazoapp.com>'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
