defaults: &defaults
  fake_notifications_enabled: false
  notify_specific_owners_only: false
  specific_owners: []


development:
  <<: *defaults

test:
  <<: *defaults
  fake_notifications_enabled: true

staging:
  <<: *defaults

production:
  <<: *defaults
