defaults: &defaults
  app_name: Zazo FriendFinder
  app_name_key: friendfinder
  version: 0.2.0
  email_notification_from: support@zazoapp.com

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
