defaults: &defaults
  app_name: Zazo FriendFinder
  app_name_key: friendfinder
  version: 0.10.6-wip.1
  email_notification_from: 'Zazo <support@zazoapp.com>'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
