defaults: &defaults
  app_name: Zazo Friend Finder
  version: 0.1.0
  authentication_method: digest

development:
  <<: *defaults
  authentication_method: basic
  stub_mobile_number: true

test:
  <<: *defaults

production:
  <<: *defaults
