defaults: &defaults
  app_name: Zazo Friend Finder
  app_name_key: friendfinder
  version: 0.1.0

development:
  <<: *defaults
  authentication_method: basic
  stub_mobile_number: true

test:
  <<: *defaults

production:
  <<: *defaults
